load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "service_proto",
    srcs = [
        "service.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//proto/entity:entity_proto",
    ],
)
