name: buf-push
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      # TODO: restore after commit to master
      # - uses: bufbuild/buf-breaking-action@v1
        # with:
          # Check breaking changes against master
            # against: 'https://github.com/andrewtsun25/djin-proto.git#branch=master,ref=HEAD~1'
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
